---
title:                                  Slick Slider
tagline:                                Preview
date:                                   2023-03-02 00:00:00
description: >
                                        Slick is a responsive carousel jQuery plugin that
                                        supports multiple breakpoints, CSS3 transitions,
                                        touch events/swiping and much more.

categories:                             [ Previewer ]
tags:                                   [ Slick, Slider ]

image:
  path:                                 /assets/images/parsa/masthead/banner-img.png
  width:                                410
  height:                               580
  alt:                                  Banner Image

comments:                               false
fab_menu_id:                            open_toc
regenerate:                             true
permalink:                              /pages/public/previewer/slick/

resources:                              [ clipboard, rouge, slick ]
---

// Page Initializer
// =============================================================================
// Enable the Liquid Preprocessor
:page-liquid:

// Set (local) page attributes here
// -----------------------------------------------------------------------------
// :page--attr:                         <attr-value>
:images-dir:                            {imagesdir}/pages/roundtrip/100_present_images

//  Load Liquid procedures
// -----------------------------------------------------------------------------
{% capture load_attributes %}themes/{{site.template.name}}/procedures/global/attributes_loader.proc{%endcapture%}

// Load page attributes
// -----------------------------------------------------------------------------
{% include {{load_attributes}} scope="none" %}

// Page content
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// https://github.com/EdwardBalaj/Simple-DeepL-API-Integration

// Include sub-documents (if any)
// -----------------------------------------------------------------------------
[role="dropcap"]
The last carousel you'll ever need.

Slick is a responsive carousel jQuery plugin that supports multiple
breakpoints, CSS3 transitions, touch events/swiping and much more.

[role="mb-4"]
Find by the following examples what Slick can do.

== Posts Slider

lorem:sentences[3]

slick::featured_post_slider[]

[role="mb-4"]
lorem:sentences[3]


== Responsive Slider

lorem:sentences[5]

slick::reponsive_slider[]

lorem:sentences[3]

[role="mt-5"]
== Features

* Fully responsive. Scales with its container
* Separate settings per breakpoint
* Uses CSS3 when available. Fully functional when not
* Swipe enabled. Or disabled, if you prefer
* Desktop mouse dragging
* Infinite looping
* Fully accessible with arrow key navigation
* Add, remove, filter & unfilter slides
* Autoplay, dots, arrows, callbacks, and more
